version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
    # stdin_open: true # Keep STDIN open for the pty
    # tty: true        # Allocate a pseudo-TTY

networks:
  app-network:
    driver: bridge 